docs: add platform engineering projects 2022
bytebase/star-history pull request #275
Opened 2023-01-19 06:15 UTC by milasuperstar

Signed-off-by: Mila Wu <wumila1996@gmail.com>

2023-01-19 08:07 UTC, adela-bytebase commented
@milasuperstar it's better to add links to Spotify, Apache Lucene and etc?

2023-01-19 09:32 UTC, milasuperstar commented
> @milasuperstar maybe it's better to add links to Spotify, Apache Lucene and etc?
I added the link for lucene, methinks the readers can google the rest hahaha (don't want the post to be filled with links lmao

2023-01-19 12:02 UTC, tianzhou commented on public/blog/star-history-yearly-pick-2022-platform-engineering.md
> +Now you have a fully private and deployable platform engineering system, but is there any other core components that have not been mentioned?
```suggestion
The above projects will constitute a pretty solid platform engineering backbone, while there are a couple of other core components worth mentioning.
```

2023-01-19 12:03 UTC, tianzhou commented on public/blog/star-history-yearly-pick-2022-platform-engineering.md
> +- Security platform (login, VPN, Audit Log, intrusion detection)
```suggestion
- Security platform (login, VPN, Audit Log, intrusion detection) - [Snyk](https://snyk.io/), [tailscale](https://tailscale.com/).
```

2023-01-19 12:05 UTC, tianzhou commented on public/blog/star-history-yearly-pick-2022-platform-engineering.md
> +- Resource platform (expansion and contraction, scheduling, FinOps)
```suggestion
- Resource platform (auto-scaling, scheduling, FinOps) [OpenCost](http://opencost.io/)
```

2023-01-19 12:07 UTC, tianzhou commented on public/blog/star-history-yearly-pick-2022-platform-engineering.md
> +- Configuration platform (application configurations, feature flags)
```suggestion
- Configuration platform (application configurations, feature flags) [Apollo](https://github.com/apolloconfig/apollo), [Flagsmith](https://flagsmith.com/).
```

2023-01-19 12:07 UTC, tianzhou commented on public/blog/star-history-yearly-pick-2022-platform-engineering.md
> +- Database development platform (for database change & query management)
```suggestion
- Database development platform (database change, query, admin, security management) - [Bytebase](https://bytebase.com)
```

2023-01-19 12:07 UTC, tianzhou commented on public/blog/star-history-yearly-pick-2022-platform-engineering.md
> +Sidenote: if you are interested in database development platforms, we’d recommend [Bytebase](https://www.bytebase.com/). As for the other items, DM us [@StarHistoryHQ](https://twitter.com/StarHistory
```suggestion
```

2023-01-20 02:18 UTC, tianzhou requested changes

2023-01-20 02:18 UTC, tianzhou commented on public/blog/star-history-yearly-pick-2022-platform-engineering.md
> +[Temporal](https://github.com/temporalio/temporal) is another rising stat and serves as a core piece in platform engineering. It is a microservice task scheduling execution platform that executes app
```suggestion
[Temporal](https://github.com/temporalio/temporal) is another rising star and serves as a core piece in platform engineering. It is a microservice task scheduling execution platform that executes application logic units, workflows in a resilient way, automatically handles intermittent failures, and retries failed operations. Although the first release only came in 2020.2, the founders built Cadence workflow (uber/cadence) back in Uber to solve Uber's workflow/orchestration problems, and Temporal is a commercialized fork version of Cadence.
```

2023-01-20 02:18 UTC, tianzhou commented on public/blog/star-history-yearly-pick-2022-platform-engineering.md
> +## Platform engineering is the future
```suggestion
## Platform Engineering is the Future
```

2023-01-20 02:18 UTC, tianzhou commented on public/blog/star-history-yearly-pick-2022-platform-engineering.md
> +- Code hosting and CI/CD - GitLab
```suggestion
- Code hosting, CI/CD, and DevSecOps - GitLab
```

2023-01-20 02:18 UTC, tianzhou commented on public/blog/star-history-yearly-pick-2022-platform-engineering.md
> +- Database development platform (database change, query, admin, security management) - [Bytebase](https://bytebase.com)
```suggestion
- Security and Access Control (network access, software supply chain, intrusion detection, Audit Log) - [Snyk](https://snyk.io/), [tailscale](https://tailscale.com/), [Vault](https://www.hashicorp.com/products/vault), [Boundary](https://www.boundaryproject.io/).
- Resource Allocation (auto-scaling, scheduling, FinOps) - [OpenCost](http://opencost.io/).
- Configuration (application configurations, feature flags) - [Apollo](https://github.com/apolloconfig/apollo), [Flagsmith](https://flagsmith.com/).
- Database Development (database change, query, admin, security) - [Bytebase](https://bytebase.com).
```

2023-01-20 02:18 UTC, tianzhou commented on public/blog/star-history-yearly-pick-2022-platform-engineering.md
> +- Managing all of the above resources (and the others) in code - Terraform
```suggestion
- Manage all cloud resources and many of the above resources (and the others) in code - Terraform
```

2023-01-20 02:18 UTC, tianzhou commented on public/blog/data.json
> +    "title": "Star History Yearly Pick 2022 | Platform Engineering",
```suggestion
    "title": "Star History Open Source 2022 | Platform Engineering",
```

2023-01-20 03:43 UTC, tianzhou approved these changes
LGTM

2023-01-20 03:44 UTC, merged